<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <DefaultLanguage>zh-Hans</DefaultLanguage>
        <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
        <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
        <OutputType>WinExe</OutputType>

        <!-- WinUI 3 -->
        <UseWinUI>true</UseWinUI>
        <WinUISDKReferences>false</WinUISDKReferences>
        <EnableMsixTooling>true</EnableMsixTooling>
        <WindowsPackageType>MSIX</WindowsPackageType>

        <!-- Project Options -->
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>IPAbuyer</RootNamespace>

        <!-- App Options -->
        <UseRidGraph>true</UseRidGraph>
        <Platforms>x64;ARM64</Platforms>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <RuntimeIdentifiers Condition="$([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)')) &gt;= 8">
            win-x64;win-arm64</RuntimeIdentifiers>
        <RuntimeIdentifiers Condition="$([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)')) &lt; 8">
            win10-x64;win10-arm64</RuntimeIdentifiers>
        <PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
        <PackageReleaseNotes>更新日志见：https://github.com/ipabuyer/ipabuyer/blob/main/CHANGELOG.md</PackageReleaseNotes>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/ipabuyer/ipabuyer</RepositoryUrl>
        <Copyright>Copyright © 2025-2026 IPAbuyer. 保留所有权利。</Copyright>
        <PackageProjectUrl>https://github.com/ipabuyer/ipabuyer</PackageProjectUrl>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Platform)' == 'x64' And '$(RuntimeIdentifier)' == ''">
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Platform)' == 'ARM64' And '$(RuntimeIdentifier)' == ''">
        <RuntimeIdentifier>win-arm64</RuntimeIdentifier>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="Assets\*.png" />
        <Content Include="Assets\*.ico">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.4.0" />
        <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3" />
        <ProjectReference Include="IPAbuyer.Core\IPAbuyer.Core.csproj" />
        <ProjectReference Include="IPAbuyer.Pages\IPAbuyer.Pages.csproj" />
        <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2705" />
        <Manifest Include="$(ApplicationManifest)" />

        <Content Include="Include\ipatool-2.3.2-windows-amd64.exe" Condition="'$(Platform)' == 'x64' Or '$(RuntimeIdentifier)' == 'win-x64' Or '$(RuntimeIdentifier)' == 'win10-x64'">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <TargetPath>ipatool.exe</TargetPath>
            <IncludeInPackage>true</IncludeInPackage>
        </Content>

        <Content Include="Include\ipatool-2.3.2-windows-arm64.exe" Condition="'$(Platform)' == 'ARM64' Or '$(RuntimeIdentifier)' == 'win-arm64' Or '$(RuntimeIdentifier)' == 'win10-arm64'">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <TargetPath>ipatool.exe</TargetPath>
            <IncludeInPackage>true</IncludeInPackage>
        </Content>
    </ItemGroup>

    <!-- 
        Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
        Tools extension to be activated for this project even if the Windows App SDK Nuget
        package has not yet been restored.
    -->
    <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
        <ProjectCapability Include="Msix" />
    </ItemGroup>
    <ItemGroup>
        <Compile Remove="IPAbuyer.Core\**\*.cs" />
        <Compile Remove="IPAbuyer.Core.Execution\**\*.cs" />
        <Compile Remove="IPAbuyer.Pages\**\*.cs" />
        <Compile Remove="IPAbuyer.Tests\**\*.cs" />
        <Page Remove="IPAbuyer.Pages\**\*.xaml" />
        <None Remove="IPAbuyer.Pages\**\*.xaml" />
        <Page Remove="IPAbuyer.Tests\**\*.xaml" />
        <None Remove="IPAbuyer.Tests\**\*.xaml" />
    </ItemGroup>
    <ItemGroup>
        <TrimmerRootDescriptor Include="ILLink.Descriptors.xml" />
    </ItemGroup>

    <!-- 
        Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution 
        Explorer "Package and Publish" context menu entry to be enabled for this project even if 
        the Windows App SDK Nuget package has not yet been restored.
    -->
    <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
        <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
        <ApplicationIcon>Assets\Icon.ico</ApplicationIcon>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
      <NoWarn></NoWarn>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|ARM64'">
      <NoWarn></NoWarn>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
      <NoWarn></NoWarn>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|ARM64'">
      <NoWarn></NoWarn>
    </PropertyGroup>

    <!-- Publish Properties -->
    <PropertyGroup>
        <PublishReadyToRun>False</PublishReadyToRun>
        <PublishTrimmed>True</PublishTrimmed>
        <TrimMode>full</TrimMode>
        <EnableTrimAnalyzer>True</EnableTrimAnalyzer>
        <SuppressTrimAnalysisWarnings>False</SuppressTrimAnalysisWarnings>
        <TrimmerSingleWarn>True</TrimmerSingleWarn>
        <ILLinkTreatWarningsAsErrors>False</ILLinkTreatWarningsAsErrors>
        <PublishProtocol>FileSystem</PublishProtocol>
        <PublishDir>bin\$(Configuration)\$(TargetFramework)\$(RuntimeIdentifier)\publish\</PublishDir>
        <SelfContained>true</SelfContained>
        <PublishSingleFile>False</PublishSingleFile>
        <PlatformTarget>$(Platform)</PlatformTarget>
        <SignAssembly>False</SignAssembly>
        <GenerateTemporaryStoreCertificate>True</GenerateTemporaryStoreCertificate>
        <GenerateAppInstallerFile>False</GenerateAppInstallerFile>
        <AppxPackageSigningEnabled>False</AppxPackageSigningEnabled>
        <AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
        <AppxAutoIncrementPackageRevision>False</AppxAutoIncrementPackageRevision>
        <GenerateTestArtifacts>False</GenerateTestArtifacts>
        <AppxBundle>Always</AppxBundle>
        <AppxBundlePlatforms>x64|arm64</AppxBundlePlatforms>
        <HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>
        <AppxSymbolPackageEnabled>False</AppxSymbolPackageEnabled>
    </PropertyGroup>
</Project>
